[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.16"

[rpc_endpoints]
anvil = "http://localhost:8545/"
goerli = "https://ethereum-goerli-rpc.allthatnode.com"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config